// Ambient augmentation for secrets that are *not* Cloudflare bindings.
//
// `cloudflare-env.d.ts` is generated by `npm run cf-typegen` (`wrangler
// types`) from `wrangler.jsonc`'s bindings (D1, KV, Vectorize, Queue, AI,
// etc.) and is gitignored — it's regenerated per clone/CI run, never
// committed. Secrets set via `wrangler secret put` (and their local
// `.dev.vars` equivalents) never appear in `wrangler.jsonc`, so `wrangler
// types` has no way to know about them and never adds them to the
// generated `CloudflareEnv` interface.
//
// `CloudflareEnv` is a plain global `interface`, so TypeScript's
// declaration merging lets us extend it here with the secret keys the app
// actually reads via `env.<NAME>` — this file is committed and always
// present, regardless of whether `cf-typegen` has been re-run.
//
// See `.env.example` for the full secrets contract and how to set each one
// locally (`.dev.vars`) vs. in production (`wrangler secret put`).
export {};

declare global {
  interface CloudflareEnv {
    /** M3: constant-time-compared login password (`POST /api/auth/login`). */
    AUTH_PASSWORD: string;
    /** M3: read-only demo-mode password, scoped to `DEMO_DB`. Public by design — see README. */
    DEMO_PASSWORD: string;
    /** M3: HMAC key for the signed session cookie. */
    SESSION_SIGNING_SECRET: string;
  }
}
